#!/usr/bin/env node
// Auto-organize the repo. Intended to run after merges to main.
//
// What it does:
//   1. Bumps `updated` to today on any project whose folder has changed
//      since the last commit on this branch (best-effort; with --all,
//      bumps every project).
//   2. Regenerates projects/INDEX.md — a flat index of every project,
//      grouped by category, with badges.
//   3. Optionally writes a platforms-grouped index when --view platforms.
//
// Usage:
//   node scripts/organize.mjs                   # default: write INDEX.md, no `updated` bumps
//   node scripts/organize.mjs --bump-updated    # also bump `updated` on changed projects
//   node scripts/organize.mjs --all             # bump `updated` everywhere
//   node scripts/organize.mjs --view platforms  # write a platforms-grouped index

import { execSync } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';

import {
  REPO_ROOT, PROJECTS_DIR,
  readJson, writeJson, findProjects, projectNameFromPath, categoryFromPath,
  parseArgs, color, header, today,
} from './lib/repo.mjs';

const args = parseArgs(process.argv.slice(2));

const projects = await findProjects();

if (projects.length === 0) {
  console.log(color('gray', 'No projects yet — nothing to organize.'));
  process.exit(0);
}

console.log(header(`Organizing ${projects.length} project${projects.length === 1 ? '' : 's'}...\n`));

// ---- 1. bump `updated` ----
if (args['bump-updated'] || args.all) {
  const changed = args.all ? new Set(projects) : changedProjectDirs(projects);
  let bumped = 0;
  for (const dir of changed) {
    const metaPath = join(dir, 'fermata.json');
    try {
      const meta = await readJson(metaPath);
      const newDate = today();
      if (meta.updated !== newDate) {
        meta.updated = newDate;
        await writeJson(metaPath, meta);
        bumped++;
      }
    } catch (err) {
      console.warn(color('yellow', `skip: ${relative(REPO_ROOT, dir)} (${err.message})`));
    }
  }
  console.log(`${color('green', 'updated')} bumped on ${bumped} project${bumped === 1 ? '' : 's'}.`);
}

// ---- 2. INDEX.md (or platforms view) ----
if (args.view === 'platforms') {
  await writePlatformsIndex(projects);
} else {
  await writeCategoryIndex(projects);
}

console.log('');
console.log(color('green', 'Done.'));

// ---------------- helpers ----------------

function changedProjectDirs(allProjects) {
  // Use git to find files changed in the last commit. If git fails or there's
  // no last commit, return an empty set (safer than touching everything).
  let changedFiles;
  try {
    const out = execSync('git diff --name-only HEAD~1 HEAD', {
      cwd: REPO_ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    });
    changedFiles = out.split('\n').filter(Boolean);
  } catch {
    return new Set();
  }
  const result = new Set();
  for (const file of changedFiles) {
    for (const dir of allProjects) {
      const rel = relative(REPO_ROOT, dir);
      if (file.startsWith(rel + '/') || file === rel) {
        result.add(dir);
        break;
      }
    }
  }
  return result;
}

async function loadAll(projects) {
  const out = [];
  for (const dir of projects) {
    try {
      const meta = await readJson(join(dir, 'fermata.json'));
      out.push({ dir, meta });
    } catch (err) {
      console.warn(color('yellow', `skip: ${relative(REPO_ROOT, dir)} (${err.message})`));
    }
  }
  return out;
}

async function writeCategoryIndex(projects) {
  const loaded = await loadAll(projects);
  const byCategory = new Map();
  for (const p of loaded) {
    const cat = p.meta.category || categoryFromPath(p.dir) || 'uncategorized';
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat).push(p);
  }

  const sortedCats = [...byCategory.keys()].sort();
  const lines = [
    '# Project Index',
    '',
    '*Auto-generated by `npm run organize`. Don\'t edit by hand — re-run the script.*',
    '',
    `Total projects: **${loaded.length}**`,
    '',
  ];

  for (const cat of sortedCats) {
    lines.push(`## ${cat}`);
    lines.push('');
    lines.push('| Project | Status | Platforms | Description |');
    lines.push('| --- | --- | --- | --- |');
    const rows = byCategory.get(cat).sort((a, b) => (a.meta.name || '').localeCompare(b.meta.name || ''));
    for (const p of rows) {
      const rel = relative(PROJECTS_DIR, p.dir);
      const link = `[${p.meta.displayName || p.meta.name}](${rel}/)`;
      const status = `\`${p.meta.status || 'unknown'}\``;
      const platforms = (p.meta.platforms || []).map((x) => `\`${x}\``).join(' ');
      const desc = (p.meta.description || '').replace(/\|/g, '\\|');
      lines.push(`| ${link} | ${status} | ${platforms} | ${desc} |`);
    }
    lines.push('');
  }

  await writeFile(join(PROJECTS_DIR, 'INDEX.md'), lines.join('\n'), 'utf8');
  console.log(`${color('green', 'wrote')}   projects/INDEX.md`);
}

async function writePlatformsIndex(projects) {
  const loaded = await loadAll(projects);
  const byPlatform = new Map();
  for (const p of loaded) {
    for (const plat of (p.meta.platforms || ['unknown'])) {
      if (!byPlatform.has(plat)) byPlatform.set(plat, []);
      byPlatform.get(plat).push(p);
    }
  }

  const sortedPlats = [...byPlatform.keys()].sort();
  const lines = [
    '# Projects by Platform',
    '',
    '*Auto-generated by `npm run organize -- --view platforms`. A project listed under more than one platform really does target all of them.*',
    '',
  ];

  for (const plat of sortedPlats) {
    lines.push(`## ${plat}`);
    lines.push('');
    const rows = byPlatform.get(plat).sort((a, b) => (a.meta.name || '').localeCompare(b.meta.name || ''));
    for (const p of rows) {
      const rel = relative(PROJECTS_DIR, p.dir);
      lines.push(`- [${p.meta.displayName || p.meta.name}](${rel}/) — ${p.meta.description || ''}`);
    }
    lines.push('');
  }

  await writeFile(join(PROJECTS_DIR, 'INDEX.platforms.md'), lines.join('\n'), 'utf8');
  console.log(`${color('green', 'wrote')}   projects/INDEX.platforms.md`);
}
